# SELECT K-MEANS ALGORITHM

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split

In [2]:
dataset=pd.read_csv('pre_processed_dataset.csv')
dataset

,age,blood_pressure,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,blood_glucose_random,...,packed_cell_volume,white_blood_cell_count,red_blood_cell_count,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,peda_edema,aanemia,class
0,48.0,80.0,1.020,1.0,0.0,0.61,1.0,0.0,0.0,121.00,...,44.0,7800.0,5.200,1.0,1.0,0.0,1.0,0.0,0.0,0.0
1,7.0,50.0,1.020,4.0,0.0,0.31,1.0,0.0,0.0,168.29,...,38.0,6000.0,4.325,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,62.0,80.0,1.010,2.0,3.0,1.00,1.0,0.0,0.0,423.00,...,31.0,7500.0,3.716,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,48.0,70.0,1.005,4.0,0.0,1.00,0.0,1.0,0.0,117.00,...,32.0,6700.0,3.900,1.0,0.0,0.0,0.0,1.0,1.0,0.0
4,51.0,80.0,1.010,2.0,0.0,1.00,1.0,0.0,0.0,106.00,...,35.0,7300.0,4.600,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,1.00,1.0,0.0,0.0,140.00,...,47.0,6700.0,4.900,0.0,0.0,0.0,1.0,0.0,0.0,1.0
396,42.0,70.0,1.025,0.0,0.0,1.00,1.0,0.0,0.0,75.00,...,54.0,7800.0,6.200,0.0,0.0,0.0,1.0,0.0,0.0,1.0
397,12.0,80.0,1.020,0.0,0.0,1.00,1.0,0.0,0.0,100.00,...,49.0,6600.0,5.400,0.0,0.0,0.0,1.0,0.0,0.0,1.0
398,17.0,60.0,1.025,0.0,0.0,1.00,1.0,0.0,0.0,114.00,...,51.0,7200.0,5.900,0.0,0.0,0.0,1.0,0.0,0.0,1.0
399,58.0,80.0,1.025,0.0,0.0,1.00,1.0,0.0,0.0,131.00,...,53.0,6800.0,6.100,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [3]:
dataset.isnull().sum()

age                        0
blood_pressure             0
specific_gravity           0
albumin                    0
sugar                      0
red_blood_cells            0
pus_cell                   0
pus_cell_clumps            0
bacteria                   0
blood_glucose_random       0
blood_urea                 0
serum_creatinine           0
sodium                     0
potassium                  0
haemoglobin                0
packed_cell_volume         0
white_blood_cell_count     0
red_blood_cell_count       0
hypertension               0
diabetes_mellitus          0
coronary_artery_disease    0
appetite                   0
peda_edema                 0
aanemia                    0
class                      0
dtype: int64

In [4]:
def selectkbest(x,y,n):
    test=SelectKBest(score_func=chi2,k=n)
    fit=test.fit(x,y)
    selectK_features=fit.transform(x)
    return selectK_features

In [5]:
def split_scalar(x,y):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
    sc=StandardScaler()
    x_train=sc.fit_transform(x_train)
    x_test=sc.transform(x_test)
    return x_train,x_test,y_train,y_test

In [6]:
def cm_prediction(classifier,x_test):
    y_pred=classifier.predict(x_test)
    from sklearn.metrics import confusion_matrix
    cm=confusion_matrix(y_test,y_pred)
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import classification_report
    accuracy=accuracy_score(y_test,y_pred)
    report=classification_report(y_test,y_pred)
    return classifier,accuracy,report,x_test,y_test,classifier

In [7]:
def Logistic(x_train,y_train,x_test):
    from sklearn.linear_model import LogisticRegression
    classifier=LogisticRegression()
    classifier.fit(x_train,y_train)
    cm,accuracy,report,x_test,y_test,classifier=cm_prediction(classifier,x_test)
    return cm,accuracy,report,x_test,y_test,classifier

In [8]:
def svm_linear(x_train,y_train,x_test):
    from sklearn.svm import SVC
    classifier=SVC(kernel='linear',random_state=0)
    classifier.fit(x_train,y_train)
    cm,accuracy,report,x_test,y_test,classifier=cm_prediction(classifier,x_test)
    return cm,accuracy,report,x_test,y_test,classifier

In [9]:
def svmnl(x_train,y_train,x_test):
    from sklearn.svm import SVC
    classifier=SVC(kernel='rbf',random_state=0)
    classifier.fit(x_train,y_train)
    cm,accuracy,report,x_test,y_test,classifier=cm_prediction(classifier,x_test)
    return cm,accuracy,report,x_test,y_test,classifier

In [10]:
def NaivesBayes(x_train,y_train,x_test):
    from sklearn.naive_bayes import GaussianNB
    classifier=GaussianNB()
    classifier.fit(x_train,y_train)
    cm,accuracy,report,x_test,y_test,classifier=cm_prediction(classifier,x_test)
    return cm,accuracy,report,x_test,y_test,classifier

In [11]:
def KNN(x_train,y_train,x_test):
    from sklearn.neighbors import KNeighborsClassifier
    classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
    classifier.fit(x_train,y_train)
    cm,accuracy,report,x_test,y_test,classifier=cm_prediction(classifier,x_test)
    return cm,accuracy,report,x_test,y_test,classifier

In [12]:
def DecisionTree(x_train,y_train,x_test):
    from sklearn.tree import DecisionTreeClassifier
    classifier=DecisionTreeClassifier(criterion='entropy',random_state=0)
    classifier.fit(x_train,y_train)
    cm,accuracy,report,x_test,y_test,classifier=cm_prediction(classifier,x_test)
    return cm,accuracy,report,x_test,y_test,classifier

In [13]:
def RandomForest(x_train,y_train,x_test):
    from sklearn.ensemble import RandomForestClassifier
    classifier=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
    classifier.fit(x_train,y_train)
    cm,accuracy,report,x_test,y_test,classifier=cm_prediction(classifier,x_test)
    return cm,accuracy,report,x_test,y_test,classifier

In [14]:
def selectk_classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf):
    dataframe=pd.DataFrame(index=['chisquare'],columns=['Logistic',
                                                        'SVML',
                                                        'SVMNL',
                                                        'NaivesBayes',
                                                        'KNN',
                                                        'DecisionTree',
                                                        'RandomForest'])
    for number,index in enumerate(dataframe.index):
        dataframe['Logistic']    [index]  = acclog[number]
        dataframe['SVML']        [index]  = accsvml[number]
        dataframe['SVMNL']       [index]  = accsvmnl[number]
        dataframe['NaivesBayes'] [index]  = accnav[number]
        dataframe['KNN']         [index]  = accknn[number]
        dataframe['DecisionTree'][index]  = accdes[number]
        dataframe['RandomForest'][index]  = accrf[number]
    return dataframe

In [15]:
df1=dataset
df1=pd.get_dummies(df1,drop_first=True)
df1

,age,blood_pressure,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,blood_glucose_random,...,packed_cell_volume,white_blood_cell_count,red_blood_cell_count,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,peda_edema,aanemia,class
0,48.0,80.0,1.020,1.0,0.0,0.61,1.0,0.0,0.0,121.00,...,44.0,7800.0,5.200,1.0,1.0,0.0,1.0,0.0,0.0,0.0
1,7.0,50.0,1.020,4.0,0.0,0.31,1.0,0.0,0.0,168.29,...,38.0,6000.0,4.325,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,62.0,80.0,1.010,2.0,3.0,1.00,1.0,0.0,0.0,423.00,...,31.0,7500.0,3.716,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,48.0,70.0,1.005,4.0,0.0,1.00,0.0,1.0,0.0,117.00,...,32.0,6700.0,3.900,1.0,0.0,0.0,0.0,1.0,1.0,0.0
4,51.0,80.0,1.010,2.0,0.0,1.00,1.0,0.0,0.0,106.00,...,35.0,7300.0,4.600,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,1.00,1.0,0.0,0.0,140.00,...,47.0,6700.0,4.900,0.0,0.0,0.0,1.0,0.0,0.0,1.0
396,42.0,70.0,1.025,0.0,0.0,1.00,1.0,0.0,0.0,75.00,...,54.0,7800.0,6.200,0.0,0.0,0.0,1.0,0.0,0.0,1.0
397,12.0,80.0,1.020,0.0,0.0,1.00,1.0,0.0,0.0,100.00,...,49.0,6600.0,5.400,0.0,0.0,0.0,1.0,0.0,0.0,1.0
398,17.0,60.0,1.025,0.0,0.0,1.00,1.0,0.0,0.0,114.00,...,51.0,7200.0,5.900,0.0,0.0,0.0,1.0,0.0,0.0,1.0
399,58.0,80.0,1.025,0.0,0.0,1.00,1.0,0.0,0.0,131.00,...,53.0,6800.0,6.100,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [16]:
x=df1.drop('class',axis=1)
y=df1['class']

In [27]:
kbest = selectkbest(x,y,6)
acclog   = []
accsvml  = []
accsvmnl = []
accknn   = []
accnav   = []
accdes   = []
accrf    = []

In [28]:
kbest

array([[1.0000e+00, 1.2100e+02, 3.6000e+01, 1.2000e+00, 4.4000e+01,
        7.8000e+03],
       [4.0000e+00, 1.6829e+02, 1.8000e+01, 8.0000e-01, 3.8000e+01,
        6.0000e+03],
       [2.0000e+00, 4.2300e+02, 5.3000e+01, 1.8000e+00, 3.1000e+01,
        7.5000e+03],
       ...,
       [0.0000e+00, 1.0000e+02, 2.6000e+01, 6.0000e-01, 4.9000e+01,
        6.6000e+03],
       [0.0000e+00, 1.1400e+02, 5.0000e+01, 1.0000e+00, 5.1000e+01,
        7.2000e+03],
       [0.0000e+00, 1.3100e+02, 1.8000e+01, 1.1000e+00, 5.3000e+01,
        6.8000e+03]])

In [29]:
x_train,x_test,y_train,y_test = split_scalar(kbest,y)

In [30]:

classifier,accuracy,report,x_test,y_test,cm = Logistic(x_train,y_train,x_test)
acclog.append(accuracy)
classifier,accuracy,report,x_test,y_test,cm = svm_linear(x_train,y_train,x_test)
accsvml.append(accuracy)
classifier,accuracy,report,x_test,y_test,cm = svmnl(x_train,y_train,x_test)
accsvmnl.append(accuracy)
classifier,accuracy,report,x_test,y_test,cm = NaivesBayes(x_train,y_train,x_test)
accknn.append(accuracy)
classifier,accuracy,report,x_test,y_test,cm = KNN(x_train,y_train,x_test)
accnav.append(accuracy)
classifier,accuracy,report,x_test,y_test,cm = DecisionTree(x_train,y_train,x_test)
accdes.append(accuracy)
classifier,accuracy,report,x_test,y_test,cm = RandomForest(x_train,y_train,x_test)
accrf.append(accuracy)

C:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [31]:
result = selectk_classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)
result

          Logistic  SVML SVMNL NaivesBayes   KNN DecisionTree RandomForest
chisquare     0.97  0.98  0.97        0.97  0.94         0.99            1